version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: pet_price_db
    restart: always
    environment:
      POSTGRES_USER: petpriceuser
      POSTGRES_PASSWORD: petpricepassword
      POSTGRES_DB: petpricedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petpriceuser -d petpricedb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
